dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - gfortran
        - g++-5
        - cmake
    env: COMPILER=gcc GCC=5

before_install:
  - export CXX=g++-$GCC CC=gcc-$GCC

install:
  - sudo add-apt-repository -y ppa:acooks/libwebsockets6
  - sudo apt-get update
  # install dependencies for uWebSockets
  - sudo apt-get install libssl-dev libuv1-dev
  # install Eigen
  - git clone --branch 3.3.7 https://github.com/eigenteam/eigen-git-mirror.git
  - pushd eigen-git-mirror
  - mkdir build && cd build
  - cmake .. && sudo make install
  - popd

script:
  # build EKF project
  - pushd EKF
  - mkdir build && cd build
  - cmake .. && make
  - popd
  # build UKF project
  - pushd UKF
  - mkdir build && cd build
  - cmake .. && make
  - popd